name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: crazy-robot1
          region: europe-west1
          source: .
          flags: --allow-unauthenticated
          env_vars: |
            APPOPTIONS__DbConnectionString=${{ secrets.DBCONNECTIONSTRING }}
            APPOPTIONS__GcsBucket=${{ secrets.GCS_BUCKET }}
            APPOPTIONS__JwtSecret=${{ secrets.JWTSECRET }}
            MQTT__Broker=${{ secrets.MQTT_BROKER }}
            MQTT__HOST=${{ secrets.MQTT_HOST }}
            MQTT__TOKEN=${{ secrets.MQTT_TOKEN }}
            MQTT__PublishEngineTopic=${{ secrets.PUBLISHENGINETOPIC }}
            MQTT__SubscribeEngineTopic=${{ secrets.SUBSCRIBEENGINETOPIC }}
            MQTT__PublishCommandsTopic=${{ secrets.PUBLISHCOMMANDSTOPIC }}
            MQTT__SubscribeCommandsTopic=${{ secrets.SUBSCRIBECOMMANDSTOPIC }}
            MQTT__DistanceWarningTopic=${{ secrets.DISTANCEWARNINGTOPIC }}
            MQTT__NegativeDistanceWarningTopic=${{ secrets.NEGATIVEDISTANCEWARNINGTOPIC }}
            MQTT__RobotOwner=${{ secrets.ROBOTOWNER }}
            MQTT__BatteryLevelInfo=${{ secrets.BATTERYLEVELINFO }}
            MQTT__ServoCommandTopic=${{ secrets.SERVOCOMMANDTOPIC }}

      - run: echo "${{ steps.deploy.outputs.url }}"
