name: API tests with .NET + TestContainers

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  local_development:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - uses: docker/setup-buildx-action@v3
        
      - name: Build
        run: dotnet build /server/CrazyRobot.sln

      - name: Test
        run: dotnet test /server/CrazyRobot.sln